# Generated by Django 3.1.6 on 2021-03-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0005_activegames_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegames',
            name='host_name',
        ),
    ]
