# Generated by Django 3.1.6 on 2021-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0006_remove_activegames_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegames',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
