# Generated by Django 3.1.6 on 2021-03-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0007_activegames_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegames',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
