# Generated by Django 3.1.6 on 2021-03-14 12:22

from django.db import migrations, models
import main_menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0009_auto_20210314_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegames',
            name='data',
            field=models.JSONField(default=main_menu.models.get_default_game_data),
        ),
    ]
