# Generated by Django 3.1.7 on 2021-04-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0011_auto_20210317_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveGames',
            new_name='Games',
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.games')),
            ],
        ),
    ]
