# Generated by Django 3.1.7 on 2021-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0012_auto_20210404_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='player_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='players',
            name='status',
            field=models.CharField(default='in_lobby', max_length=255),
        ),
    ]
